=== robertocompanyzestudios/Dam-Vscode/LMarcas/XSD/Tareas/5.4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice>
                                <xs:element name="varon"/>
                                <xs:element name="femenino"/>
                            </xs:choice>
                            <xs:element name="direccion" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle" type="tipoNombre"></xs:element>
                                        <xs:element name="poblacion" type="tipoNombre"></xs:element>
                                        <xs:element name="provincia" type="tipoNombre"></xs:element>
                                        <xs:element name="cpostal" type="tipoCodPostal"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nacimiento" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                          <xs:attribute name="dia" type="tipoDia"/>
                                          <xs:attribute name="mes" type="tipoMes"/>
                                          <xs:attribute name="anyo" type="tipoAnyo"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nombre" type="xs:string">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipoDia">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="31"/>
      </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoMes">
      <xs:restriction base="xs:string">
        <xs:enumeration value="Enero"/>
          <xs:enumeration value="Febrero"/>
          <xs:enumeration value="Marzo"/>
          <xs:enumeration value="Abril"/>
          <xs:enumeration value="Mayo"/>
          <xs:enumeration value="Junio"/>
          <xs:enumeration value="Julio"/>
          <xs:enumeration value="Agosto"/>
          <xs:enumeration value="Septiembre"/>
          <xs:enumeration value="Noviembre"/>
          <xs:enumeration value="Octubre"/>
          <xs:enumeration value="Diciembre"/>
      </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoAnyo">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1900"/>
        <xs:maxInclusive value="2011"/>
      </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoCodPostal">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="10000"/>
        <xs:maxInclusive value="99999"/>
      </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipoNombre">
      <xs:restriction base="xs:string">
        <xs:maxLength value="50"/>
      </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== robertocompanyzestudios/Dam-Vscode/LMarcas/XSD/Tareas/5.4.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="5.4.xsd">
    <persona>
        <varon/>

        <direccion>
            <calle>caoba, 1</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28005</cpostal>
        </direccion>

        <nacimiento dia="10" mes="Abril" anyo="1982"></nacimiento>

        <nombre>Juan Pardo</nombre>

    </persona>

    <persona>
        <femenino/>

        <direccion>
            <calle>Roncato, 1</calle>
            <poblacion>Llescas</poblacion>
            <provincia>Toledo</provincia>
            <cpostal>45200</cpostal>
        </direccion>
        <direccion>
            <calle>Paseo de la Esperanza, 15, 1ºA</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28005</cpostal>
        </direccion>

        <nombre>María López</nombre>

    </persona>

</personas>
